### ISSUE TITLE
Contracts losing who they are assigned to

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#33] opened 2016-01-20 20:33 UTC
Contracts are losing who they are assigned to.  I found the following

FLOOR COVERING SERVICES
CONCESSIONAIRE SERVICES
FIREFIGHTERS' PROTECTIVE GEAR
AGGREGATE AND STONE III
FIRE FIGHTER PROTECTIVE GEAR GLOVES
Plumbing Supplies
PQ CONTRACT FOR PRINTING SERVICES
AUTOMATED VEHICLE SHARING SERVICES

all listed in all contracts with no one assigned to them.  I am sure than some of those were previously assigned to Stephanie/ed and finished.

**Comment by rileystewart** [comment] 2016-01-20 20:35
I think some of these I picked to remove from Conductor.  and now they are back on randomly but also back w/o their original assignment.  If I have selected to remove them from Conductor I don't want them to show up under all Items.

**Comment by bsmithgall** [comment] 2016-01-20 20:39
I'm not sure what you mean. They were finished and then you removed the new ones but they are showing up by mistake? It's unclear if you want them to be present or absent from the conductor all list. If you want them to be present and they are unassigned, you should just be able to re-assign them.

**Comment by rileystewart** [comment] 2016-01-20 20:50
I'm not really sure what the problem is.  We originally assigned every single contract in Conductor to either Stephanie or Ed.  I did a dump today and noticed that there were 8 contracts that were listed as 'unassigned'.  

With the 2 firefighter contracts and concessionaire I am positive that we selected 'remove from conductor'.  These should not be coming up under all contracts because we selected to remove them.

With Plumbing Supplies, Stephanie finished that contract so it should show back under all contracts with her name.

As for the PQ printing contract...that one I'm very confused by because the expiration date is incorrect...but it must have been updated via conductor so it should have who it was originally assigned to

**Comment by bsmithgall** [comment] 2016-01-20 20:53
Is this a dump from the download files? Are you sure they are in the all contracts list in Conductor? It's possible they are incorrectly showing up in the file when they shouldn't be.

**Comment by rileystewart** [comment] 2016-01-20 20:59
The dump made me realize it and drew my attention to the all contracts list.  The biggest issue is the ones that I manually removed from conductor (concession, firefighter) coming back and showing up again under all contracts.  This seems to be something that has happened within the last week

**Comment by bsmithgall** [comment] 2016-01-21 01:52
The two firefighter contracts and the concessionaire contract all have the "visible in conductor" flag set to on, so I think just removing them as before should fix that.

For the plumbing supplies, that's in the complete step but hasn't been finished (it looks like the final info hasn't been set on it yet like controller number, etc.)

I'm not sure about the PQ for printing services, but altogether it looks like from the perspective of the software things are fine, so I'm going to go ahead and close this ticket.

**Closed as completed by bsmithgall** 2016-01-21 01:52 UTC

**Comment by rileystewart** [comment] 2016-01-29 16:01
This happened again.  I edited a contract spec in admin because it was incorrect. When I went back into conductor this contract is now 'unassigned'. Automated Vehicle Sharing Services II

**Comment by bsmithgall** [comment] 2016-01-29 18:21
I can't see anything in the logs to indicate why this would be, and I can't reproduce it locally. It might have something to do with the underlying issue that is causing #44 where database sessions aren't closing properly.
